name: Simple CI/CD Demo

on:
  push:
    branches:
      - main
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello world"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "welcome to nu"